name = "recaptcha-waf" # name of the worker for cloudflare
main = "src/cloudflare_worker.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat_v2" ]

[vars]
# please set these values if you want to deploy the worker
API_KEY = ""
PROJECT_NUMBER = ""
ACTION_SITE_KEY = ""
SESSION_SITE_KEY = ""
CHALLENGE_PAGE_SITE_KEY = ""
EXPRESS_SITE_KEY = ""