# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/
authors = ["Google LLC"]
description = "Library to access reCAPTCHA Enterprise from Fastly Compute."
language = "javascript"
manifest_version = 3
name = "recaptcha-fastly"

[scripts]
build = "js-compute-runtime dist/index.js bin/main.wasm"
post_init = "npm install"

[setup]
  [setup.backends]
    [setup.backends.origin]
     description = "Content or application origin"

    [setup.backends.google]
      description = "Google server that hosts the challengepage"
      address = "www.google.com"
      port = 443

    [setup.backends.recaptcha]
      description = "reCAPTCHA API origin"
      address = "public-preview-recaptchaenterprise.googleapis.com"
      port = 443

[local_server]

  [local_server.backends]

    [local_server.backends.origin]
      url = "http://127.0.0.1:18080"

    [local_server.backends.google]
      url = "http://127.0.0.1:18081"

    [local_server.backends.recaptcha]
      url = "http://127.0.0.1:18082"

  [local_server.dictionaries]

    [local_server.dictionaries.recaptcha]
      file = "dict.test.json"
      format = "json"
