# Top-level configuration
name = "browser-rendering"
main = "cf_endpoint.test.ts"
compatibility_date = "2024-09-09"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

browser = { binding = "MYBROWSER" }

[vars]
PROJECT_NUMBER = "12345"
API_KEY = "abc123"
ACTION_SITE_KEY = "action-site-key"
EXPRESS_SITE_KEY = "express-site-key"
SESSION_SITE_KEY = "session-site-key"
CHALLENGE_PAGE_SITE_KEY = "challenge-page-site-key"
RECAPTCHA_ENDPOINT = "https://recaptchaenterprise.googleapis.com"