# Top-level configuration
name = "browser-rendering"
main = "cf_endpoint.test.ts"
compatibility_date = "2024-09-09"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

browser = { binding = "MYBROWSER" }

# [vars]
# The Google API key that you created for authentication (required).
# API_KEY = ""

# Your Google Cloud project number (required).
# PROJECT_NUMBER = ""

# reCAPTCHA action-token key. This key is required if you're using action-tokens for protecting your pages.
# ACTION_SITE_KEY = ""

# reCAPTCHA session-token key. This key is required if you're using session-tokens and/or configured reCAPTCHA Javascript Injection for protecting your pages.
# SESSION_SITE_KEY = ""

# reCAPTCHA challenge-page key. This key is required if you're using the reCAPTCHA challenge page. You should use another flow key together to create an assessment to call policy to redirect to the challenge page for protecting your pages.
# CHALLENGE_PAGE_SITE_KEY = ""

# reCAPTCHA express key. This key is required if you're using the reCAPTCHA express for protecting your pages.
# EXPRESS_SITE_KEY = ""

# Set the url paths separated by semicolons for example "/example1;/example2;/example3;/*" if you should inject script on pages over html head tag reCAPTCHA session-token case (optional).
# The path for which this injection applies, specified as a glob pattern. For more information on glob, see the manual page(https://man7.org/linux/man-pages/man7/glob.7.html).
# SESSION_JS_INSTALL_PATH = ""