name: Attach Release Artifacts

on: 
  push:
    tags:
    - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-release
  cancel-in-progress: true

jobs:
  build-core:
    uses: ./.github/workflows/build_core.yml
  build-cloudflare:
    needs: build-core
    uses: ./.github/workflows/build_cloudflare.yml
  build-fastly:
    needs: build-core
    uses: ./.github/workflows/build_fastly.yml
  package:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build-core, build-cloudflare, build-fastly]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get Version
        run: |
         TAG_VERSION=$(echo "${{ github.ref }}" | cut -c 12-)
         LIB_VERSION=$(cat package.json | jq -r .version)
         CF_VERSION=$(cat bindings/cloudflare/package.json | jq -r .version)
         FASTLY_VERSION=$(cat bindings/fastly/package.json | jq -r .version)
         if [ "$LIB_VERSION" != "$TAG_VERSION" ] || [ "$LIB_VERSION" != "$CF_VERSION" ] || [ "$LIB_VERSION" != "$FASTLY_VERSION" ]; then
           echo "Error: package.json versions do not match."
           echo "Tag Version: $TAG_VERSION, Library: $LIB_VERSION, Cloudflare: $CF_VERSION, Fastly: $FASTLY_VERSION"
           exit 1
         fi
         echo "using version: $LIB_VERSION"
         echo "VERSION=$LIB_VERSION" >> "$GITHUB_OUTPUT"
        id: version
      - uses: actions/download-artifact@v4
        with:
          name: library-package
          path: pkg
      - uses: actions/download-artifact@v4
        with:
          name: cloudflare-package
          path: bindings/cloudflare/pkg
      - uses: actions/download-artifact@v4
        with:
          name: fastly-package
          path: bindings/fastly/pkg
      - run: ls
      - run: ls pkg/
      - run: ls bindings/cloudflare/pkg/
      - run: ls bindings/fastly/pkg/
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            "pkg/recaptcha_library.tar.gz"
            "bindings/cloudflare/pkg/cloudflare_client.tar.gz"
            "bindings/fastly/pkg/fastly_client.tar.gz"
