name: Build and Test Fastly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-fastly
  cancel-in-progress: true

jobs:
  build-core:
    uses: ./.github/workflows/build_core.yml
 
  fastly:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build-core
    defaults:
      run:
        working-directory: ./bindings/fastly
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - uses: actions/download-artifact@v4
        with:
          name: core-library-artifacts
          path: dist
      - run: |
          # Download and install latest fastly CLi version
          # TODO: find and parse latest version of Fastly CLI
          # This may be possible using the github REST API to list assets in a release
          # and fetching the one matching the fastly_<VERSION>_linux_amd64.deb pattern.
          wget https://github.com/fastly/cli/releases/download/v10.15.0/fastly_10.15.0_linux_amd64.deb
          sudo dpkg -i fastly_10.15.0_linux_amd64.deb
          sudo apt-get update
          sudo apt-get install -y --fix-missing
      - run: npm ci
      - run: npm run build
      - run: npm run pack
      - run: mv pkg/package.tar.gz pkg/fastly-package.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: fastly-artifacts
          path: |
           bindings/fastly/dist/*
           bindings/fastly/pkg/fastly-package.tar.gz
      - run: npm test 
