name: Build and Test Akamai

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-akamai
  cancel-in-progress: true

jobs:
  build-core:
    uses: ./.github/workflows/build_core.yml
 
  akamai:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build-core
    defaults:
      run:
        working-directory: ./bindings/akamai
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - uses: actions/download-artifact@v4
        with:
          name: core-library-dist
          path: dist
      - run: echo "Current directory - $(pwd)"
      - run: npm ci
      - run: npm run build
      # TODO: fix tests
      #- run: npm test
      - uses: actions/upload-artifact@v4
        with:
          name: akamai-artifacts
          path: bindings/akamai/dist/*
