name: Build and Test Core Library

on:
    workflow_dispatch:
    workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-core

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      id: cached-dist
      with:
        path: dist
        key: ${{ github.run_id }}
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      if: steps.cached-dist.outputs.cache-hit != 'true'
      with:
        node-version: '22.x'
        cache: 'npm'
    - run: npm ci
      if: steps.cached-dist.outputs.cache-hit != 'true'
    - run: npm run build
      if: steps.cached-dist.outputs.cache-hit != 'true'
    - run: npm test
      if: steps.cached-dist.outputs.cache-hit != 'true'
    - uses: actions/upload-artifact@v4
      if: steps.cached-dist.outputs.cache-hit != 'true'
      with:
        name: core-library-artifacts
        path: dist/*
    - run: npm run pack
      if: steps.cached-dist.outputs.cache-hit != 'true'
    - uses: actions/upload-artifact@v4
      if: steps.cached-dist.outputs.cache-hit != 'true'
      with:
        name: library-package
        path: pkg/recaptcha_library.tar.gz