name: Build and Test Cloudflare

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-cloudflare
  cancel-in-progress: true

jobs:
  build-core:
    uses: ./.github/workflows/build_core.yml

  cloudflare:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build-core
    defaults:
      run:
        working-directory: ./bindings/cloudflare
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - uses: actions/download-artifact@v4
        with:
          name: core-library-dist
          path: dist
      - run: echo "Current directory - $(pwd)"
      - run: npm ci
      - run: npm run build
      - run: npm run build:worker
      - run: npm run pack
      - run: npm test
      - name: Install and test examples
        run: |
          set -e # Exit immediately if a command exits with a non-zero status
          for example_dir in examples/*; do
            if [ -d "$example_dir" ] && [ -f "$example_dir/package.json" ]; then
              echo "-----------------------------------------"
              echo "Processing example: $example_dir"
              cd "$example_dir"
              npm install
              npm run test
              cd ../.. # Go back to the root of the project
            fi
          done
      - uses: actions/upload-artifact@v4
        with:
          name: cloudflare-dist
          path: bindings/cloudflare/dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: cloudflare-package
          path: bindings/cloudflare/pkg/cloudflare_client.tar.gz
