name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release, in the format of '1.2.3'. Must match all package.json versions.
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-release
  cancel-in-progress: true

jobs:
  build-core:
    uses: ./.github/workflows/build_core.yml
  build-cloudflare:
    needs: build-core
    uses: ./.github/workflows/build_cloudflare.yml
  build-fastly:
    needs: build-core
    uses: ./.github/workflows/build_fastly.yml
  package:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build-core, build-cloudflare, build-fastly]
    steps:
      - uses: actions/checkout@v4
      - name: Get Version
        run: |
         LIB_VERSION=$(cat package.json | jq -r .version)
         CF_VERSION=$(cat bindings/cloudflare/package.json | jq -r .version)
         FASTLY_VERSION=$(cat bindings/fastly/package.json | jq -r .version)
         if [ "$LIB_VERSION" != ${{ inputs.version }}" ] || [ "$LIB_VERSION" != "$CLOUDFLARE_VERSION" ] || [ "$LIB_VERSION" != "$CLOUDFLARE_VERSION" ]; then
           echo "Error: package.json versions do not match."
           echo "Input Version: ${{ inputs.tags }}, Library: $LIB_VERSION, Cloudflare: $CF_VERSION, Fastly: $FASTLY_VERSION"
           exit 1
         fi
         echo "using version: $LIB_VERSION"
         echo "VERSION=$LIB_VERSION" >> "$GITHUB_OUTPUT"
        id: version
      - uses: actions/download-artifact@v4
        with:
          name: core-library-artifacts
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: cloudflare-artifacts
          path: bindings/cloudflare/dist
      - uses: actions/download-artifact@v4
        with:
          name: fastly-artifacts
          path: bindings/fastly/dist
      # TODO: package and upload release
