name: Check Format

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
    workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-check-format

jobs:
  check-format:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true