name: Integration Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: .github/workflows/build_cloudflare.yml

  setup:
    strategy:
      matrix:
        node-version: [22.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

  cloudflare:
    runs-on: ubuntu-latest
    needs: [build, setup]
    defaults:
        run:
          working-directory: ./bindings/cloudflare
    strategy:
        matrix:
            node-version: [22.x]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cloudflare-artifacts-node${{ matrix.node-version }}
          path: bindings/cloudflare/dist/*
          run-id: ${{ github.event.workflow_run.id }}
      - name: Deploy to Cloudflare
        env:
            CF_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
            CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy:nobuild
     #- name: Run Integration Tests
     #   run: ./integration_test.sh