name: Integration Test Fastly

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-integrate-fastly
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build_fastly.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        working-directory: ./bindings/fastly
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: |
          # Download and install latest fastly CLi version
          # TODO: find and parse latest version of Fastly CLI
          # This may be possible using the github REST API to list assets in a release
          # and fetching the one matching the fastly_<VERSION>_linux_amd64.deb pattern.
          wget https://github.com/fastly/cli/releases/download/v10.15.0/fastly_10.15.0_linux_amd64.deb
          sudo dpkg -i fastly_10.15.0_linux_amd64.deb
          sudo apt-get update
          sudo apt-get install -y --fix-missing
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: fastly-package
          path: bindings/fastly/pkg
      - name: Publish to Fastly
        run: fastly compute publish --token ${{ secrets.FASTLY_API_TOKEN }} --service-id ${{ secrets.FASTLY_SERVICE_ID }} --package pkg/fastly_client.tar.gz
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
          FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}

  test: 
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci --prefix integration
      - name: Run Integration Tests
        run: |
          cd ./integration 
          npm test
