name: Integration Test Akamai

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-integrate-akamai
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build_akamai.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
        run:
          working-directory: ./bindings/akamai
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: akamai-artifacts
          path: bindings/akamai/dist
      - run: npm run pack
      - run: wget https://github.com/akamai/cli/releases/download/v1.6.0/akamai-v1.6.0-linuxamd64
      - run: chmod +x akamai-v1.6.0-linuxamd64
      - run: mv akamai-v1.6.0-linuxamd64 /usr/local/bin/akamai
      - run: sudo apt-get install -y jq # JSON output parser
      - run: printf "${{ secrets.AKAMAI_EDGERC }}" >> ~/.edgerc
      - run: akamai install edgeworkers
      - run: akamai ew upload --edgerc ~/.edgerc --jsonout --bundle dist/akamai.tgz ${{ secrets.AKAMAI_INTEGRATION_EW_ID }}
      - run: akamai ew list-versions --edgerc ~/.edgerc --jsonout ${{ secrets.AKAMAI_INTEGRATION_EW_ID }} | jq .data[-1].version
      - run:  |
         upload_out=$( akamai ew upload --edgerc ~/.edgerc --jsonout --bundle dist/akamai.tgz ${{ secrets.AKAMAI_INTEGRATION_EW_ID }} )
         latest_version=$(akamai ew list-versions --edgerc ~/.edgerc --jsonout ${{ secrets.AKAMAI_INTEGRATION_EW_ID }} | jq .data[-1].version)
         activate_out=$( akamai ew activate --edgerc ~/.edgerc --jsonout ${{ secrets.AKAMAI_INTEGRATION_EW_ID }} staging $latest_version )
    # TODO: deploy

     #- name: Run Integration Tests
     #   run: ./integration_test.sh