name: Integration Test Fastly

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-integrate-fastly
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build_fastly.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        working-directory: ./bindings/fastly
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: |
          # Download and install latest fastly CLi version
          # TODO: find and parse latest version of Fastly CLI
          # This may be possible using the github REST API to list assets in a release
          # and fetching the one matching the fastly_<VERSION>_linux_amd64.deb pattern.
          wget https://github.com/fastly/cli/releases/download/v10.15.0/fastly_10.15.0_linux_amd64.deb
          sudo dpkg -i fastly_10.15.0_linux_amd64.deb
          sudo apt-get update
          sudo apt-get install -y --fix-missing

      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: fastly-package
          path: bindings/fastly/pkg
      
      - uses: actions/download-artifact@v4
        with:
          name: core-library-dist
          path: dist

      - name: Deploy Compute@Edge Package
        run: fastly compute deploy --token ${{ secrets.FASTLY_API_TOKEN }} --service-id ${{ secrets.FASTLY_SERVICE_ID }} --package pkg/fastly_client.tar.gz
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
          FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}
          ACTION_SITE_KEY: ${{ secrets.CLOUDFLARE_ACTION_SITE_KEY }}
          SESSION_SITE_KEY: ${{ secrets.CLOUDFLARE_SESSION_SITE_KEY }}
          CHALLENGE_PAGE_SITE_KEY: ${{ secrets.CLOUDFLARE_CHALLENGE_PAGE_SITE_KEY }}
          EXPRESS_SITE_KEY: ${{ secrets.CLOUDFLARE_EXPRESS_SITE_KEY }}
          SESSION_JS_INSTALL_PATH: ${{ secrets.CLOUDFLARE_SESSION_JS_INSTALL_PATH }}
          ENDPOINT: ${{ secrets.FASTLY_ENDPOINT }}

  test:
    needs: [deploy]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./integration/playwright_tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          ENDPOINT: ${{ secrets.FASTLY_ENDPOINT }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./integration/playwright_report/
          retention-days: 30
