name: Integration Tests

on:
  workflow_run:
    workflows: [Build and Test]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  cloudflare:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
        run:
          working-directory: ./bindings/cloudflare
    strategy:
        matrix:
            node-version: [22.x]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Deploy to Cloudflare
        env:
            CF_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
            CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy:nobuild
     #- name: Run Integration Tests
     #   run: ./integration_test.sh