name: Integration Test Cloudflare

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-integrate-cloudflare
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build_cloudflare.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
        run:
          working-directory: ./bindings/cloudflare
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: cloudflare-artifacts
          path: bindings/cloudflare/dist
      - run: ls -la dist
      - run: pwd
      - name: Deploy to Cloudflare
        env:
            CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy:nobuild
     #- name: Run Integration Tests
     #   run: ./integration_test.sh