name: Integration Test Cloudflare

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-integrate-cloudflare
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build_cloudflare.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
        run:
          working-directory: ./bindings/cloudflare
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: cloudflare-artifacts
          path: bindings/cloudflare/dist
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./bindings/cloudflare
          command: deploy dist/cloudflare_worker.js --no-bundle
          secrets: |
            API_KEY
            PROJECT_NUMBER
            ACTION_SITE_KEY
            SESSION_SITE_KEY
            CHALLENGE_PAGE_SITE_KEY
            EXPRESS_SITE_KEY
            SESSION_JS_INSTALL_PATH
            ENDPOINT
        env:
          API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          PROJECT_NUMBER: ${{ secrets.CLOUDFLARE_PROJECT_NUMBER }}
          ACTION_SITE_KEY: ${{ secrets.CLOUDFLARE_ACTION_SITE_KEY }}
          SESSION_SITE_KEY: ${{ secrets.CLOUDFLARE_SESSION_SITE_KEY }}
          CHALLENGE_PAGE_SITE_KEY: ${{ secrets.CLOUDFLARE_CHALLENGE_PAGE_SITE_KEY }}
          EXPRESS_SITE_KEY: ${{ secrets.CLOUDFLARE_EXPRESS_SITE_KEY }}
          SESSION_JS_INSTALL_PATH: ${{ secrets.CLOUDFLARE_SESSION_JS_INSTALL_PATH }}
          ENDPOINT: ${{secrets.CLOUDFLARE_ENDPOINT}}
  test: 
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci --prefix integration
      - name: Run Integration Tests
        run: |
          cd ../../integration 
          npm test