# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  core-library:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/*
  
  cloudflare:
    runs-on: ubuntu-latest
    needs: core-library
    defaults:
      run:
        working-directory: ./bindings/cloudflare
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist
      - run: echo "Current directory - $(pwd)"
      - run: npm ci
      - run: npm run build
      - run: npm test

  fastly:
    runs-on: ubuntu-latest
    needs: core-library
    defaults:
      run:
        working-directory: ./bindings/fastly
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist
      - run: |
          # Download and install latest fastly CLi version
          # TODO: find and parse latest version of Fastly CLI
          # This may be possible using the github REST API to list assets in a release
          # and fetching the one matching the fastly_<VERSION>_linux_amd64.deb pattern.
          wget https://github.com/fastly/cli/releases/download/v10.15.0/fastly_10.15.0_linux_amd64.deb
          sudo dpkg -i fastly_10.15.0_linux_amd64.deb
          sudo apt-get update
          sudo apt-get install -y --fix-missing
      - run: npm ci
      - run: npm run build
      - run: npm test
